apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "security-operator.fullname" . }}
  labels:
    {{- include "security-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "security-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "security-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "security-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LDAP_URI
              value: {{ .Values.ldap.uri | quote }}
            - name: LDAP_BIND_DN
              value: {{ .Values.ldap.bindDN | quote }}
            - name: LDAP_BIND_PASSWORD
              value: {{ .Values.ldap.bindPassword | quote }}
            - name: LDAP_BASE_DN
              value: {{ .Values.ldap.baseDN | quote }}
            - name: LDAP_USERS_OU
              value: {{ printf "%s,%s" .Values.ldap.usersOU .Values.ldap.baseDN | quote }}
            - name: LDAP_GROUPS_OU
              value: {{ printf "%s,%s" .Values.ldap.groupsOU .Values.ldap.baseDN | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}